services:
  wazuh-manager:
    image: wazuh/wazuh-manager:4.13.0
    container_name: wazuh-manager
    entrypoint: /bin/bash
    command: >
      -c "mkdir -p /var/ossec/etc/rules /var/ossec/etc/decoders &&
          cp /tmp/custom/ossec.conf /var/ossec/etc/ossec.conf &&
          cp /tmp/custom/local_rules.xml /var/ossec/etc/rules/local_rules.xml &&
          cp /tmp/custom/local_decoder.xml /var/ossec/etc/decoders/local_decoder.xml &&
          chown -R wazuh:wazuh /var/ossec/etc/ &&
          exec /init"
    volumes:
      - wazuh-alerts:/var/ossec/logs/alerts
      - wazuh-etc:/var/ossec/etc
      - ./manager/ossec.conf:/tmp/custom/ossec.conf:ro
      - ./manager/local_rules.xml:/tmp/custom/local_rules.xml:ro
      - ./manager/local_decoder.xml:/tmp/custom/local_decoder.xml:ro
    ports:
      - "1514:1514"
      - "1515:1515"
    networks:
      - blue-team
    restart: unless-stopped

  wazuh-agent:
    image: wazuh/wazuh-agent:4.13.0
    container_name: wazuh-agent
    environment:
      WAZUH_MANAGER: "wazuh-manager"
      WAZUH_AGENT_NAME: "secureshop-agent"
    entrypoint: /bin/bash
    command: >
      -c "chmod 750 /var/ossec/active-response/bin/remove-webshell.sh &&
          chown root:wazuh /var/ossec/active-response/bin/remove-webshell.sh &&
          exec /init"
    volumes:
      - ../secureShop:/monitor
      - bw-logs:/var/log/bunkerweb:ro
      - ./agent/ossec.conf:/var/ossec/etc/ossec.conf
      - ./agent/remove-webshell.sh:/var/ossec/active-response/bin/remove-webshell.sh
    networks:
      - blue-team
    depends_on:
      - wazuh-manager
    restart: unless-stopped

networks:
  blue-team:
    external: true
  
volumes:
  wazuh-alerts:
    name: wazuh-alerts  
    external: true
  wazuh-etc:
  bw-logs:
    name: bw-logs
    external: true
